### ISSUE TITLE
Support for connection pooling for non transaction 

### ISSUE THREAD

**Issue by No9** [strongloop/loopback-ibmdb#11]
As discussed with @palgon and @naveen-venkat
There is and issue in https://github.com/strongloop/loopback-ibmdb/blob/master/lib/ibmdb.js where it will always use the global connection created during initialization unless a transaction is passed in through the options object
This is leading to a degradation in performance when multiple requests are made through a service
Specifically a standard loopback logon request against a db2 instance has the following profile. 
```
1user -> 0.5sec response time

19users-> 6sec response time

100users -> 30sec response time
``` 

Validated by running 
```
select * from SYSIBMADM.MON_CONNECTION_SUMMARY where session_auth_id = 'WUAAPP11'
```
Which only returned one row
Please see https://www.ibm.com/support/knowledgecenter/SSEPGG_10.5.0/com.ibm.db2.luw.sql.rtn.doc/doc/r0056510.html 
For more info on `MON_CONNECTION_SUMMARY`

**Comment by naveen-venkat** [comment]
@qpresley, I saw that the pooling issue is fixed with the connection drop, thanks for the fix.
Just wanted to know if you would be updating the package version in loopback-connector-db2, https://github.com/strongloop/loopback-connector-db2/blob/master/package.json#L23 ?

**Comment by qpresley** [comment]
@naveen-venkat Shouldn't need to, the ^ indicates to use the highest patch level of the module so it should install 1.0.6 right now.
