### ISSUE TITLE
Possible resource leak

### ISSUE THREAD

**Issue by rmg** [strongloop/loopback-ibmdb#17]
Inside `updateOrCreate()` and `replaceOrCreate()` is the same pattern:

```js
conn.commitTransaction(function(err) {
  if (err) {
    return callback && callback(err);
  }

  conn.close(function() {});
  return callback && callback(null, data, meta);
});
```

It appears, based on inspection only, that if a transaction commit fails, the connection is not returned to the pool. For a short run this wouldn't cause any problems, but it looks like if there are enough of these errors it could continue to consume resources until the connection pool is exhausted and the application is forced to exit (unless the errors are being caught and logged, in which case the application will just produce a steady stream of errors.

**Comment by qpresley** [comment]
@rmg Good catch. This definitely needs to be fixed although commit rarely fails so urgency may not be high.  If I'm making other changes to loopback-ibmdb I may fix this up.

**Comment by 0candy** [comment]
Closing this issue as PR is merged.
