### ISSUE TITLE
 Issue with Object type in loopback model

### ISSUE THREAD

**Issue by JyotiRani** [strongloop/loopback-ibmdb#51]
I have a property of type 'Object' in my model file which maps to a column in dash db. When i try to use the fields filter (e.g. http://localhost:3000/api/tasks/TSK1?filter[fields][taskCode]=false) with this type of schema, it fails with the following error stack:
Stacktrace:

undefined:1
undefined
^

SyntaxError: Unexpected token u in JSON at position 0
at Object.parse (native)
at DASHDB.IBMDB.fromColumnValue (C:\HCL\apiconnectdemo\tasks2\node_modules\l
oopback-ibmdb\lib\ibmdb.js:390:19)
at DASHDB.SQLConnector.fromRow.SQLConnector.fromDatabase (C:\HCL\apiconnectd
emo\tasks2\node_modules\loopback-ibmdb\node_modules\loopback-connector\lib\sql.j
s:1171:28)
at C:\HCL\apiconnectdemo\tasks2\node_modules\loopback-ibmdb\node_modules\loo
pback-connector\lib\sql.js:1203:19
at Array.map (native)
at C:\HCL\apiconnectdemo\tasks2\node_modules\loopback-ibmdb\node_modules\loo
pback-connector\lib\sql.js:1202:21
at C:\HCL\apiconnectdemo\tasks2\node_modules\loopback-datasource-juggler\lib
\observer.js:172:22
at doNotify (C:\HCL\apiconnectdemo\tasks2\node_modules\loopback-datasource-j
uggler\lib\observer.js:99:49)
at DASHDB.ObserverMixin._notifyBaseObservers (C:\HCL\apiconnectdemo\tasks2\n
ode_modules\loopback-datasource-juggler\lib\observer.js:122:5)
at DASHDB.ObserverMixin.notifyObserversOf (C:\HCL\apiconnectdemo\tasks2\node
_modules\loopback-datasource-juggler\lib\observer.js:97:8)
at cbForWork (C:\HCL\apiconnectdemo\tasks2\node_modules\loopback-datasource-
juggler\lib\observer.js:162:14)
at C:\HCL\apiconnectdemo\tasks2\node_modules\loopback-ibmdb\node_modules\loo
pback-connector\lib\sql.js:428:7
at C:\HCL\apiconnectdemo\tasks2\node_modules\loopback-ibmdb\lib\ibmdb.js:282
:11
at Database.db.close (C:\HCL\apiconnectdemo\tasks2\node_modules\ibm_db\lib\o
dbc.js:1530:7)
at C:\HCL\apiconnectdemo\tasks2\node_modules\loopback-ibmdb\lib\ibmdb.js:281
:14
at C:\HCL\apiconnectdemo\tasks2\node_modules\loopback-ibmdb\lib\ibmdb.js:269
:13

From the stacktrace its evident that Object field value is undefined, hence JSON.parse(undefined) is throwing the above error. Since the error is in loopback-ibmdb which is common to all the IBM connectors, can you please fix this?

**Comment by jannyHou** [comment]
@JyotiRani Can you post the versions of 
`loopback-ibmdb`
`loopback-connector`
`loopback-connector-dashdb`
 ? Thanks.

And I am trying to reproduce the error, by "Object field value is undefined", what is the row data stored in database?

**Comment by JyotiRani** [comment]
Value of the Object field is null in database i.e. no data defined for the field.
    "loopback": "^3.0.0",
    "loopback-boot": "^2.6.5",
    "loopback-connector-dashdb": "^1.0.18",
    "loopback-connector-rest": "^2.1.0",
loopback-connector: "4.2.0"
loopback-ibmdb: "1.0.12"

Note: Because of this issue, filter by fields is not working in my application.

**Comment by jannyHou** [comment]
thanks, reproduced the error on my local.

**Comment by dhmlau** [comment]
PR #52

**Comment by dhmlau** [comment]
As @jannyHou noted, when using explorer, I'm using `{"fields": {"taskCode": false}}` as filter.

**Comment by dhmlau** [comment]
Fixed in PR #52.  
To be released.

**Comment by kjdelisle** [comment]
loopback-ibmdb@2.2.1 is released!
