### ISSUE TITLE
migration.js line 71 should use escapeName

### ISSUE THREAD

**Issue by qpresley** [strongloop/loopback-ibmdb#53]
Adding a column as well as change and drop column should be using escapeName to ensure case is maintained.  As the code is currently written a property named cAsEsEnSiTiVe will be passed to the SQL interpreter as CASESENSITIVE resulting in an all uppercase column name for CREATE and a mismatch or error for CHANGE and DROP.  See lines 71, 81 and 119 in migration.js

**Comment by qpresley** [comment]
@ssh24 as you are reviewing the migration scenarios for the connectors using this module this may be easy to fix.

**Comment by cphpham** [comment]
Thank you for the solution. I just tried to use this fix, but I'm getting undefined back where I expect to get the column including the quotes.

If I check the ibdb.js file I see that IBMDB.prototype.escapeName() exists twice on #206 and #299. I assume that this is not correct and one should be IBMDB.prototype.columnEscaped() with the correct functionality?

**Comment by qpresley** [comment]
@cphpham, do you have a stack trace for the error you hit?  columnEscaped() is part of loopback-connector/lib/sql.js which is the parent class of the connector so it shouldn't be returning undefined.  Need to see the stack trace to see what the error is really complaining about.  escapeName() should not exist twice but shouldn't be the cause of the issue.

**Comment by cphpham** [comment]
@qpresley if I look into the sql.js (loopback-connector v4.2.1) I see that the footprint of the columnEscaped() changed into:

```
/**
 * Get the escaped column name for a given model property
 * @param {String} model The model name
 * @param {String} property The property name
 * @returns {String} The escaped column name
 */
SQLConnector.prototype.columnEscaped = function(model, property) {
  return this.escapeName(this.column(model, property));
};
```
It seems to work fine again when I pass the model and property name.

**Comment by qpresley** [comment]
@ssh24. Can we fix the bad calls to columnEscaped

**Comment by ssh24** [comment]
@cphpham Thank you for catching the bad calls to the `columnEscaped` function.

Created https://github.com/strongloop/loopback-ibmdb/pull/55 to fix the issue and remove the duplicate `IBMDB.prototype.escapeName` function.
