### ISSUE TITLE
Loopback model definition is not adding foreign key relation in database table

### ISSUE THREAD

**Issue by malek0512** [strongloop/loopback-ibmdb#78]
Description/Steps to reproduce
It seems loopback-ibmdb is not adding foreign key constraint in Database table as per model definition.
I am using loopback 4 for API design and data modeling.
I am using DB2 as my database.

Expected result
Foreign key constraints defined in loopback 4 model, should be reflected during table creation.

**Comment by dhmlau** [comment]
@malek0512, currently the foreign key constraints do not get added automatically.  This will be covered by this Strong Relation epic: https://github.com/strongloop/loopback-next/issues/2331.

Having said that, I have a working-in-progress example with the PostgreSQL connector.  See https://github.com/dhmlau/loopback4-coffeeshop/blob/master/src/models/review.model.ts#L5-L14.  I believe it would work similarly for other databases.

Hope it helps.

**Comment by malek0512** [comment]
@dhmlau thank you for your quick response.
I'm afraid that, this [solution](https://github.com/dhmlau/loopback4-coffeeshop/blob/master/src/models/review.model.ts#L5-L14) doesn't work neither with loopback-ibmdb module.
Is there any other way ?

A closer look into [IBMDB.prototype.createTable](https://github.com/strongloop/loopback-ibmdb/blob/master/lib/ibmdb.js#L772) method looks like there is no foreignKey logic creation.

**Comment by dhmlau** [comment]
@malek0512, I've checked with @jannyHou.. Unfortunately, the ibmdb connectors do not support foreign key discover/migrate.
Let me mark this as a feature.
