### ISSUE TITLE
updates failing because model property's columnName is being ignored

### ISSUE THREAD

**Issue by emonddr** [strongloop/loopback-ibmdb#79]
# Description/Steps to reproduce

loopback-connector-dashdb 2.0.3 
loopback-ibmdb 2.5.1 

In a situation where a model has been defined (e.g. Awards.json) and a model property (e.g. awardId) has specified a `columnName` value (e.g. AWARD_ID), certain endpoints that `update` the model experience an error because the SQL uses the model property name, instead of the columnName.

Example of model property specifying the columnName value for the dashdb connector:
```
 "awardId": {
      "type": "number",
      "id": true,
      "generated": true,
      "dashdb": {
        "columnName": "AWARD_ID"
      }
    }
```

Example of the error:

```
    loopback:connector:ibmdb IBMDB.prototype._replace stmt: {"sql":"SELECT \"awardId\" FROM  \"AWARD\" WHERE \"AWARD_ID\"=?","params":[10]} data: [] err: {"error":"[node-ibm_db] SQL_ERROR","sqlcode":-206,"message":"[IBM][CLI Driver][DB2/LINUXX8664] SQL0206N  \"awardId\" is not valid in the context where it is used.  SQLSTATE=42703\n","state":"42S22"}
```

The SELECT statement should have used `AWARD_ID` instead of `awardId`.

Certain `update` endpoints perform a `select`, followed by a `delete`, and then an `insert`.

Let's say there are two models: Award and ProgramManager.

ProgramManager hasMany Award
Award belongsTo ProgramManager

There are many endpoints generated for these two models. I will not list them all here.

However, here are the endpoints in the API Explorer that experienced failures:

PUT /ProgramManagers
(when doing update; not when doing insert)
  
PUT /ProgramManagers/{id}
     
POST /ProgramManagers/{id}/replace

POST /ProgramManagers/replaceOrCreate
 (when doing update; not when doing insert)

PUT /Awards
 (when doing update; not when doing insert)

PUT /Awards/{id}

POST /Awards/{id}/replace 

POST /Awards/replaceOrCreate
 (when doing update; not when doing insert)

# Link to reproduction sandbox

# Expected result

All the generated endpoints should work

# Additional information

**Comment by emonddr** [comment]
After further investigation, the scope of this bug is restricted to any endpoint calling
loopback-datasource-juggler/lib/dao.js  `replaceById` which ends up calling loopback-ibmdb/lib/ibmdb.js `_replace` method.  You don't need a relation between models to experience this bug. The endpoints of Award and ProgramManager are essentially the same, and no 'relation-related' endpoints are affected.  e.g. (/ProgramManagers/{id}/awards , /Awards/{id}/programManager, etc )

**Comment by dhmlau** [comment]
@emonddr, since your PR has landed, is this issue good to close?
